# Ordinal and Label Encoding!!! 
___

### Importing Libraries

In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv('customer.csv')

In [29]:
df.sample(5)

    age  gender   review education purchased
0    30  Female  Average    School        No
4    16  Female  Average        UG        No
14   15    Male     Poor        PG       Yes
32   92    Male  Average        UG       Yes
15   75    Male     Poor        UG        No

In [30]:
df = df.iloc[:,2:]

___
### Removing Age column as it is Numerical and Gender column as it is Nominal.

In [31]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train,x_test,y_train,y_test = train_test_split(
    df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2
)

In [34]:
x_train.head()

     review education
32  Average        UG
14     Poor        PG
19     Poor        PG
25     Good    School
15     Poor        UG

___
### Importing Ordinal Encoder

<b>OrdinalEncoder</b> is used to convert **ordinal categorical data** into numerical values.

It assigns a numerical value to each category based on the **order or ranking** of the categories.

In [35]:
from sklearn.preprocessing import OrdinalEncoder

___
### Defining the order of categories

Defining the **order of categories** for two ordinal categorical columns.

* For the first column, the order is:
  Poor → Average → Good
* For the second column, the order is:
  School → UG → PG

The **categories** parameter allows us to specify the correct order instead of letting the encoder decide it automatically.

The encoder will assign numerical values according to this order:

* Poor → 0, Average → 1, Good → 2
* School → 0, UG → 1, PG → 2

In [36]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [37]:
x_train = oe.fit_transform(x_train)
x_test = oe.transform(x_test)

In [38]:
x_train

array([[1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.]])

___
### Checking the Categories

oe.categories_ is used to view the **categories specified by the OrdinalEncoder**.

* First column: ['Poor', 'Average', 'Good']
* Second column: ['School', 'UG', 'PG']

The **_** at the end of categories_ indicates that this is an **attribute containing information stored by the encoder** after it has been fitted.

In [39]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

___
### Importing LabelEncoder

LabelEncoder is used to convert categorical labels into numerical values.
It assigns a unique numerical value to each category. It is commonly used for encoding the target variable in a machine learning problem.

For example, categories such as Yes and No can be converted into numerical values such as 1 and 0.

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
le = LabelEncoder()

In [44]:
y_train.head()

32    Yes
14    Yes
19    Yes
25     No
15     No
Name: purchased, dtype: object

In [45]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [46]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1])

___
### Checking the Classes

le.classes_ displays all the categories in the order in which LabelEncoder has assigned their numerical labels.

For example, if the categories are **no,yes** the classes may be displayed in alphabetical order. The position of each category determines its encoded numerical value.

In [48]:
le.classes_

array(['No', 'Yes'], dtype=object)

___
### Thats all from Ordinal and Label Encoding Section !!!
___